
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/team03-m23-9am-2
owner: ucsb-cs156-m23
repo_name: team03-m23-9am-2
pull_requests: [{"author":{"id":"U_kgDOBh3juQ","is_bot":false,"login":"andrewthaii","name":""},"headRefName":"Andrew-UcsbOrganization-pages","number":66,"title":"Andrew UCSBOrganization Review #15 #16 #17 #18 #19 #20 #21 #22","url":"https://github.com/ucsb-cs156-m23/team03-m23-9am-2/pull/66"}]
