
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/team03-m23-9am-2
owner: ucsb-cs156-m23
repo_name: team03-m23-9am-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjM5ODM3OTM5","is_bot":false,"login":"cjyu81","name":"Charlie"},"headRefName":"Charlie-MenuItemReview-#34","number":61,"title":"Charlie menu item review #34","url":"https://github.com/ucsb-cs156-m23/team03-m23-9am-2/pull/61"},{"author":{"id":"MDQ6VXNlcjM5ODM3OTM5","is_bot":false,"login":"cjyu81","name":"Charlie"},"headRefName":"Charlie-MenuItemReview-#33","number":60,"title":"Charlie menu item review #33","url":"https://github.com/ucsb-cs156-m23/team03-m23-9am-2/pull/60"},{"author":{"id":"MDQ6VXNlcjM5ODM3OTM5","is_bot":false,"login":"cjyu81","name":"Charlie"},"headRefName":"Charlie-MenuItemReview-team02port","number":56,"title":"add 4 files from team02","url":"https://github.com/ucsb-cs156-m23/team03-m23-9am-2/pull/56"}]
